### ISSUE TITLE
Racecondition in `runtime.cu`

### ISSUE THREAD

**Issue by psychocoderHPC** [SimeonEhrig/CUDA-Runtime-Interpreter#1]
There is a race condition in the example `runtime.cu`. All threads within the kernel writing to the same variable ([link](https://github.com/SimeonEhrig/CUDA-Runtime-Interpreter/blob/42d40dbffa6391c07e7249d1c551b1e242ac8e2b/example_prog/runtime.cu#L6)).

There are several ways to fix it:
- use `atomicExchange` to assign a value
- start only one thread on the device
- allocate an integer for each thread

**Comment by SimeonEhrig** [comment]
Thanks for the hint. I added a vector, to do real parallel work without dependencies.
